config/routes.rb
Rails.application.routes.draw do
  resources :contact, only: [:create]
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: true
  attribute :message, validate: true

  def headers
    {
      subject: "Contact Form: #{name}",
      to: "anthonycmarion@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  add_flash_types :alert, :notice
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    @contact = Contact.new(contact_params)
    if @contact.deliver
      redirect_to '/', notice: 'Message sent. Thank you!'
    else
      flash.now.alert = "Try again. Error sending message."
      render 'pages/home', status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]
  def home
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anthony Marion Portfolio</title>
     <%= favicon_link_tag 'am_favicon.svg' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <div>
      <%= render "shared/navbar" %>
        <%= render "shared/flashes" %>
      <div>
        <%= yield %>
      </div>
    </div>
    <div class="bottom-0">
      <%= render "shared/footer" %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
  </body>

app/views/pages/home.html.erb
<%# BANNER %>
<section class="flex flex-col justify-center px-4 md:px-8 mx-auto max-w-8xl py-20 min-h-full md:min-h-screen">
  <h1 class="text-4xl h-56 md:text-5xl mt-10 lg:text-6xl max-w-3xl" data-controller="typed" data-typed-strings-value="<%= ["Hey👋 I'm Anthony.
      <br>
      I'm a junior software engineer passionate about creating solutions with code."].to_json %>"></h1>
      <div class="relative flex justify-center items-center md:absolute md:bottom-0 md:mb-16 md:left-0 md:right-0">
        <%= link_to "#about-me" do %>
          <i class="icon-caret-right"></i>
          <img src="<%=asset_path("down-icon.svg")%>" class="animate-pulse h-8 w-auto md:mt-0">
        <% end %>
      </div>
</section>

<%# ABOUT ME %>
<div class="py-20 bg-teal-900" id="about-me">
  <%= render 'shared/container' do %>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-16">
      <img src="<%=asset_path("Anthony_Marion_profile-min.jpg")%>" alt="Profile Image" class="w-32 h-auto col-span-1 mb-8 rounded-sm transform -rotate-3 shadow-lg">
      <div class="col-span-2">
        <p class="text-teal-300 text-sm font-mono uppercase tracking-wider mb-2">But first</p>
        <h3 class="text-4xl mb-4 text-white font-sans">A bit of background</h3>
        <div class="space-y-4">
          <p class="lg:my-0 lg:mt-4 text-md font-light text-teal-50/80 leading-relaxed text-justify">I started my career in ecommerce and marketing, helping small business build their online presence and grow their customer base. Throughout my roles, I worked closely with software developers. I saw the power of technology in driving the bottom-line and increasing conversions and became fascinated by the world of coding.</p>
          <p class="lg:my-0 lg:mt-4 text-md font-light text-teal-50/80 leading-relaxed text-justify">I realised that by coding I could have an even greater impact on the businesses I worked with. So I decided to take the leap and transition my career to become a software engineer. I enrolled in a  coding bootcamp and dedicated every spare moment to learning and practicing my new skills.</p>
          <p class="lg:my-0 lg:mt-4 text-md font-light text-teal-50/80 leading-relaxed text-justify">And now I look to fuse my e-Commerce expertise with my new coding skills to create solutions that help businesses thrive in the digital world.</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%# EXPERIENCE %>
<section class="pt-20">
  <%= render 'shared/container' do %>
    <h3 class="text-4xl mb-4 text-black font-sans">Experience and education</h3>
    <p class="lg:my-0 lg:mt-4 text-md text-gray-500 font-light leading-relaxed text-justify">I have spent a number of years in the front-line trenches of digital marketing and e-Commerce. It's here I built my skills and earned myself some pieces of 'paper' along the way.</p>

    <div class="my-8">
      <p class="text-xl tracking-tight font-medium mb-2 text-black">Work</p>
      <div class="divide-y divide-gray-300">
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2020 - 2022</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">e-Commerce Manager</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">UGT International</p>
        </div>
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2019 - 2020</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">e-Commerce Assistant</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">UGT International</p>
        </div>
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2015 - 2019</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">Digital Marketing & e-Commerce Assistant</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">SimCorner</p>
        </div>
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2011 - 2014</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">Founder</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">Mister Brady & Co.</p>
        </div>
      </div>
    </div>

    <div class="my-8">
      <p class="text-xl tracking-tight font-medium mb-2 text-black">School</p>
      <div class="divide-y divide-gray-300">
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2023</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">Web Development Bootcamp</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">Le Wagon Melbourne</p>
        </div>
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2012</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">Graduate Diploma of Maketing</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">Swinburne University of Technology</p>
        </div>
        <div class="py-4">
          <p class="font-mono text-teal-500 text-xs">2011</p>
          <p class="text-md text-black leading-relaxed text-justify font-medium">Bachelor Of Business</p>
          <p class="text-md text-gray-500 leading-relaxed text-justify font-light">Swinburne University of Technology</p>
        </div>
      </div>
    </div>
  <% end %>
</section>

<%# TECH STACK %>
<section class="py-10" id="tech">
  <div class="mx-auto md:max-w-5xl">
    <div class="bg-slate-900 md:rounded-sm px-4 md:px-8 py-10">
      <h3 class="text-sm tracking-tight font-base mb-8 text-slate-500 text-center">Technologies I use</h3>
      <div class="text-teal-300 grid grid-cols-3 md:grid-cols-6 gap-8 max-w-2xl mx-auto">
        <div>
          <img src="<%=asset_path("aws.svg")%>" alt="AWS-logo" class="transform hover:scale-75 transition duration-600 object-cover pt-4 px-4">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">AWS</p>
        </div>

        <div>
          <img src="<%=asset_path("css3.svg")%>" alt="CSS-logo" class="transform hover:scale-75 transition duration-600 object-cover pt-4 px-4">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">CSS</p>
        </div>

        <div>
          <img src="<%=asset_path("html5.svg")%>" alt="HTML-logo" class="transform hover:scale-75 transition duration-600 object-cover pt-4 px-4">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">HTML</p>
        </div>

        <div>
          <img src="<%=asset_path("react.svg")%>" alt="React-logo" class="transform hover:scale-75 transition duration-600 object-cover pt-4 px-4">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">React</p>
        </div>

        <div>
          <img src="<%=asset_path("ruby.svg")%>" alt="Ruby-logo" class="transform hover:scale-75 transition duration-600 object-cover pt-4 px-4">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">Ruby</p>
        </div>

        <div>
          <img src="<%=asset_path("javascript_1.svg")%>" alt="JS-logo" class="object-cover pt-4 px-4 transform hover:scale-75 transition duration-600">
          <p class="text-sm tracking-tight font-base pt-4 text-slate-500 text-center">Javascript</p>
        </div>
      </div>
    </div>
  </div>
</section>

<%# PORTFOLIO %>
<section class="mx-auto max-w-5xl px-4 md:px-8 py-20 min-h-96 md:min-h-screen py-10" id="portfolio">
  <h3 class="text-4xl mb-4 text-black font-sans mb-8">Projects I've been working on</h3>
  <div class="content">

    <%# ON-BOARD %>
    <div class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-10">
      <div class="content">
        <p class="text-teal-300 text-sm font-mono uppercase tracking-wider mb-2">Fullstack Web App</p>
        <p class="text-md leading-relaxed text-black text-justify text-xl font-bold capitalize mb-2">on board</p>
        <p class="text-gray-500 text-sm leading-relaxed text-justify font-light mb-4">Ruby On Rails - JavaScript - Tailwind - Heroku</p>
        <p class="text-md text-gray-500 leading-relaxed text-justify font-light">A new app that lets New Caledonian boat owners rent out their boats to tourists who are keen to take part in a range of exciting activities, including surfing, fishing, snorkeling, and more. With the ability to book directly through the app, tourists can easily find the perfect boat to suit their needs, and take to the crystal-clear waters of New Caledonia's pristine lagoon.
        </p>
        <p class="mt-4 text-md text-gray-500 leading-relaxed text-justify font-light">Optimised for desktop.</p>
        <a class="clickable-icon fa-brands fa-github mt-2" href="https://github.com/JohanBinst/on-board" target="_blank"></a>
      </div>

      <div class="image">
        <%= link_to image_tag(asset_path("On_board_hero.png"), class:"object-cover shadow-[rgba(0,_0,_0,_0.24)_0px_3px_8px] rounded-lg", alt: "On Board"), "https://feeling-blue.herokuapp.com/", target: "_blank" %>
      </div>
    </div>
    <hr class="mt-8">

    <%# AM BLOG %>
    <div class="mt-10 grid grid-cols-1 md:grid-cols-2 gap-10">
      <div class="content">
        <p class="text-teal-300 text-sm font-mono uppercase tracking-wider mb-2">Fullstack Web App</p>
        <p class="text-md leading-relaxed text-black text-justify text-xl font-bold capitalize mb-2">IYRTIAMI</p>
        <p class="text-gray-500 text-sm leading-relaxed text-justify font-light mb-4">Ruby On Rails - JavaScript - Tailwind - Heroku</p>
        <p class="text-md text-gray-500 leading-relaxed text-justify font-light">Introducing IYRTIAMI, a micro blog site that I coded and designed from scratch. This lightweight blog chronicles my journey into the coding world - warts and all. I make regular updates to the UX and UI, and continue to build new features to ensure visitors enjoy the best possible experience. Stay tuned for more exciting updates.
        </p>
        <a class="clickable-icon fa-brands fa-github mt-2" href="https://github.com/AntcMan/Blog.git" target="_blank"></a>
      </div>

      <div class="image">
        <%= link_to image_tag(asset_path("IYRTIAMI_hero.png"), class:"object-cover shadow-[rgba(0,_0,_0,_0.24)_0px_3px_8px] rounded-lg", alt: "On Board"), "https://anthony-blog.herokuapp.com/", target: "_blank" %>
      </div>
    </div>
    <hr class="mt-8">

    <%# ANTHONY PROFILE %>
    <div class="mt-10 grid grid-cols-1 md:grid-cols-2 gap-10">
      <div class="content">
        <p class="text-teal-300 text-sm font-mono uppercase tracking-wider mb-2">Design & Development</p>
        <p class="text-md leading-relaxed text-black text-justify text-xl font-bold mb-2">My portfolio</p>
        <p class="text-gray-500 text-sm leading-relaxed text-justify font-light mb-4">Ruby - Rails - JavaScript - Tailwind - SCSS</p>
        <p class="text-md text-gray-500 leading-relaxed text-justify font-light">My portfolio website showcases my coding projects and demonstrates my skills and experience as a developer. It's built using Ruby on Rails, Tailwind CSS and JavaScript.</p>
        <a class="clickable-icon fa-brands fa-github mt-2" href="https://github.com/AntcMan/ANTHONY-COM" target="_blank"></a>
      </div>

      <div class="image">
        <%= link_to image_tag(asset_path("Anthony_profile_website.png"), class:"shadow-[rgba(0,_0,_0,_0.24)_0px_3px_8px] object-cover rounded-lg", alt: "Anthony Marion Profile"), "https://github.com/AntcMan/ANTHONY-COM", target: "_blank" %>
      </div>
    </div>
  </div>
</section>

<%# CONTACT %>
<section class="bg-teal-900 py-20" id="contact-anthony">
  <%= render 'shared/container' do %>
  <p class="text-teal-300 text-sm font-mono uppercase tracking-wider mb-2">Want to chat?</p>
  <h1 class="text-4xl mb-4 text-white font-sans">Drop me a line</h1>
  <p class="lg:my-0 lg:mt-4 text-md font-light text-teal-50/80 leading-relaxed text-justify pb-5">Feel free to write me a message below and I will get back to you.</p>

    <%= form_for :contact, url: contact_index_path do |f| %>
      <%= f.text_field :name, placeholder: "NAME", class: "mb-5 mr-5 bg-transparent placeholder-teal-50/80 text-teal-50/80 font-light font-mono w-full", id:"name-field" %>
      <%= f.text_field :email, placeholder: "WORK EMAIL", class: "mb-5 bg-transparent placeholder-teal-50/80 text-teal-50/80 font-light font-mono w-full" %><br>
      <div class="flex md:mt-4">
        <%= f.text_area :message, placeholder: "MESSAGE", class: "mb-5 bg-transparent placeholder-teal-50/80 text-teal-50/80 font-light font-mono w-full md:flex-1" %>
      </div>
      <br>
      <%= f.button 'SEND', type: 'submit', class: 'bg-gray-900 px-5 text-white font-light font-mono uppercase hover:text-white hover:bg-black py-2 px-5 rounded-sm' %>
    <% end %>
  <% end %>
</section>

app/views/shared/_container.html.erb
<div class="mx-auto md:max-w-2xl px-4 md:px-8">
  <%= yield %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<hr>
  <div class="max-w-8xl mx-auto py-5 flex flex-col md:flex-row justify-between items-center">
    <div class="text-center md:text-left mb-4 md:mb-0 md:mr-4">
      <p class="ml-5 text-md text-gray-500 leading-relaxed text-justify px-5"> &copy;<%= Time.current.year %> coded with 💪🏽 by Anthony Marion </p>
      <%# <p class="ml-5 text-md text-gray-500 leading-relaxed text-justify px-5"> &copy;2023 - coded with 💪🏽 by Anthony Marion </p> %>
    </div>
    <div class="footer-icons md:text-right">
      <div class="icons px-5">
        <a class="clickable-icon fa-brands fa-github px-3" href="https://github.com/AntcMan" target="_blank"></a>
        <a class="clickable-icon fa-brands fa-linkedin-in px-3" href="https://www.linkedin.com/in/anthony-marion-71b0a0257/" target="_blank"></a>
        <a class="clickable-icon fa-sharp fa-regular fa-envelope px-3" href="mailto:anthonycmarion@gmail.com" target="_blank"></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="backdrop-blur-lg backdrop-saturate-150 bg-white/80 navbar navbar-expand-sm navbar-light
            navbar-lewagon z-40 fixed top-0 left-0 transition
            duration-300 transition-opacity w-screen"
            data-controller="navbar" data-action="scroll@window->navbar#onScroll" data-navbar-ypos-value="<%= request.path == '/' ? '200' : '20' %>">
  <div class="max-w-8xl mx-auto px-4 px-8 py-4 flex flex-wrap items-center justify-between">
    <a href="#" class="inline-block">
        <span class="self-center text-lg font-semibold whitespace-nowrap">ANTHONY MARION</span>
    </a>
    <button data-collapse-toggle="navbar-solid-bg" type="button" class="inline-flex items-center p-4 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-solid-bg" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto font-mono uppercase tracking-widest" id="navbar-solid-bg">
      <ul class="flex flex-col items-center mt-4 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-transparent">
        <li>
          <a href="#tech" class="block py-2 pl-3 pr-4 text-gray-500 rounded hover:underline underline-offset-4 md:hover:bg-transparent md:border-0 md:hover:text-gray-900 md:p-0 ">Tech</a>
        </li>
        <li>
          <a href="#portfolio" class="block py-2 pl-3 pr-4 text-gray-500 rounded hover:underline underline-offset-4 md:hover:bg-transparent md:border-0 md:hover:text-gray-900 md:p-0">Projects</a>
        </li>
        <li>
          <a href="#contact-anthony" class="block py-2 pl-3 pr-4 text-gray-500 rounded hover:underline underline-offset-4 md:hover:bg-transparent md:border-0 md:hover:text-gray-900 md:p-0">Contact</a>
        </li>
        <%# There was a 9d='download' attribute I removed (maybe this was important) %>
        <%= link_to "Resume", asset_path('/docs/Anthony_Marion_CV.pdf'), target: "_blank", class: 'bg-gray-900 text-white hover:text-white hover:bg-black py-2 px-5 rounded-sm' %>
      </ul>
    </div>
  </div>
</nav>